/*
 * Copyright (c) 2026 Alayra Systems Pvt. Limited (Pakistan)
 * & Alayra Systems LLC (USA).
 *
 * Alayra Nexus™ is a trademark of Alayra Systems. Use of the name or logo
 * is not granted by the software license below.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * A copy of the License is in the LICENSE file at the repository root,
 * or at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the License for details.
 */

// Creating the standalone database on first run (Phase S2.4).
//
// A Postgres deployment runs `prisma migrate deploy` as a separate step, because an operator who
// has provisioned a database is also running a deploy pipeline. A standalone gateway has neither:
// `npx @alayra/nexus` is a single command in a directory that may contain nothing at all, and the
// first thing it has to do is build its own database. There is no Prisma CLI to invoke — it is a
// dev dependency, absent from a published package — and no network to fetch one.
//
// So the DDL is committed as plain SQL (prisma/sqlite-schema.sql, generated by `prisma migrate
// diff`, never hand-written) and executed here against an empty file.
//
// CORRECTION (S3): the claim above that there is "no Prisma CLI to invoke" is no longer true and
// was load-bearing — it is the reason one would conclude a guided move to Postgres is impossible.
// `prisma` now sits in `dependencies`, the `prisma/` directory ships in `files`, and
// scripts/npm/postinstall.js resolves and spawns that CLI on every install. lib/prismaCli.ts uses
// the same resolution to run `migrate deploy` against a database the operator is moving TO. None of
// that changes the reasoning for THIS file: a first-run SQLite file needs a schema once and will
// never be upgraded in place, so committed DDL remains right here.
//
// WHY THIS IS NOT A MIGRATION SYSTEM, and must not quietly become one: it creates a schema, once,
// in a database that has none. It cannot upgrade an existing one. A gateway whose file already has
// tables is left strictly alone — the alternative is a "helpful" boot that alters someone's data
// without being asked. Upgrading a standalone database across versions is Phase S3, and until it
// exists, refusing loudly is the honest behaviour.
//
// The preflight check cannot substitute for this: `SELECT 1` succeeds against an empty SQLite file,
// so a gateway with no tables passes every dependency check and then fails on its first real query
// with "no such table" — long after the point where a good message was possible.

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { PrismaClient } from '@prisma/client';

/**
 * Where the committed DDL lives, relative to this module.
 *
 * `../../prisma` resolves correctly from both `src/lib` (tsx, development) and `dist/lib`
 * (compiled), because `dist` sits at the same depth as `src`. Anything cleverer here — a cwd-based
 * path, an import — breaks in exactly one of those two cases, and it is always the compiled one.
 */
const DDL_PATH = resolve(__dirname, '..', '..', 'prisma', 'sqlite-schema.sql');

/** What `ensureSqliteSchema` did, so the caller can say so rather than guessing. */
export interface SchemaBootstrapResult {
  created: boolean;
  /** Tables present after the call. */
  tables: number;
}

/** Application tables currently in the file, ignoring SQLite's own bookkeeping. */
async function countTables(client: PrismaClient): Promise<number> {
  const rows = await client.$queryRawUnsafe<{ n: number | bigint }[]>(
    `SELECT COUNT(*) AS n FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'`,
  );
  return Number(rows[0]?.n ?? 0);
}

/**
 * Split the DDL into statements.
 *
 * Naive on purpose, and safe here for one specific reason: this file is generated by Prisma from a
 * schema with no triggers, no stored procedures and no string literal containing a semicolon — so a
 * semicolon at the end of a line is always a statement boundary. If the schema ever grows something
 * that breaks that assumption, the post-run table count in `ensureSqliteSchema` is what catches it —
 * and the parity test asserts the statement count matches the CREATE statements in the file, so a
 * mis-split shows up as a failed test rather than a half-built database.
 */
function statements(sql: string): string[] {
  return sql
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('--'))
    .join('\n')
    .split(';')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Create the schema if — and only if — the database has none.
 *
 * Idempotent by the check, not by the SQL: the DDL is plain `CREATE TABLE`, which fails loudly on a
 * second run. That is the desired shape. A silent `IF NOT EXISTS` everywhere would let a partially
 * created database limp onward looking healthy.
 */
export async function ensureSqliteSchema(client: PrismaClient): Promise<SchemaBootstrapResult> {
  const before = await countTables(client);
  if (before > 0) return { created: false, tables: before };

  let ddl: string;
  try {
    ddl = readFileSync(DDL_PATH, 'utf8');
  } catch (e) {
    throw new Error(
      `Standalone mode needs its database schema, and ${DDL_PATH} could not be read ` +
      `(${(e as Error).message}). This file ships with the package; if it is missing, the install ` +
      `is incomplete. Run \`npm run db:sqlite-schema\` from a source checkout to regenerate it.`,
      { cause: e },
    );
  }

  const stmts = statements(ddl);
  if (stmts.length === 0) {
    throw new Error(`${DDL_PATH} contains no SQL statements — refusing to report an empty database as ready.`);
  }

  // One transaction: a schema that half-exists is worse than one that does not exist at all,
  // because the next boot would find tables, skip this entirely, and fail on the missing ones.
  await client.$transaction(async (tx) => {
    for (const s of stmts) await tx.$executeRawUnsafe(s);
  });

  const after = await countTables(client);
  if (after === 0) {
    throw new Error(`Ran ${stmts.length} statements from ${DDL_PATH} but the database still has no tables.`);
  }

  return { created: true, tables: after };
}
