-- Bring the migrations back into agreement with schema.prisma.
--
-- Nothing here changes how the gateway behaves. It exists so that the NEXT migration anyone writes
-- is about what they changed, and nothing else.
--
-- ── What had drifted, and how it was measured ─────────────────────────────────────────────────
--
-- `prisma migrate diff --from-migrations prisma/migrations --to-schema-datamodel prisma/schema.prisma`
-- against a throwaway PostgreSQL reported nineteen statements. Two causes, both accumulated over
-- eighteen migrations written by hand:
--
--   1. DEFAULTS THE SCHEMA DOES NOT DECLARE. Early migrations gave `id` a `gen_random_uuid()`
--      default and `updatedAt` a `CURRENT_TIMESTAMP` one. Prisma's `@default(uuid())` and
--      `@updatedAt` are generated by the CLIENT, so the model declares no database default and
--      these never fire — every insert in this codebase goes through Prisma, and there is no raw
--      INSERT anywhere that could rely on them. Dropping them is metadata-only and instant.
--
--   2. FOREIGN KEYS MISSING `ON UPDATE CASCADE`. Confirmed against a migrated database rather than
--      by reading SQL: every ON DELETE action already MATCHES the schema exactly — CASCADE for the
--      three that cascade, SET NULL for the two that null. Only ON UPDATE differed, NO ACTION where
--      Prisma's default is CASCADE. It has never mattered because ON UPDATE fires only when a
--      primary key VALUE changes, and every key here is a uuid that is written once.
--
-- So this is genuinely cosmetic — and it was worth fixing precisely because it is. Left alone, the
-- next person to run `prisma migrate dev` for a one-line change gets those nineteen statements
-- folded into their migration, and either ships them unread or unpicks them under time pressure.
-- Migration 0017 in this same directory is what that costs when it goes unnoticed: a table sat in
-- the schema for months with no migration creating it, so every FRESH Postgres install was missing
-- it, and the backup export — the first feature to walk every table — died on those installs.
--
-- ── The one cost worth knowing about ──────────────────────────────────────────────────────────
--
-- Re-adding a foreign key makes PostgreSQL verify every existing row, and `TokenUsage` is by far
-- the largest table here. On a gateway with a long history this migration will take noticeably
-- longer than the others and holds a lock on that table while it runs. It is a deploy-time
-- operation and it happens once. Splitting it into `NOT VALID` plus a later `VALIDATE CONSTRAINT`
-- would not help: Prisma runs each migration in a single transaction, so the validation would hold
-- the same lock regardless.

-- ── Defaults the schema does not declare ──────────────────────────────────────────────────────

ALTER TABLE "AdminApiToken"     ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "AdminRecoveryCode" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "NexusTeamKey"      ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "TokenUsage"        ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "AdminAuth"     ALTER COLUMN "updatedAt" DROP DEFAULT;

ALTER TABLE "AppSettings"   ALTER COLUMN "id" DROP DEFAULT,
                            ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "DomainAlias"   ALTER COLUMN "id" DROP DEFAULT,
                            ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "NexusKey"      ALTER COLUMN "id" DROP DEFAULT,
                            ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "NexusProvider" ALTER COLUMN "id" DROP DEFAULT,
                            ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Team"          ALTER COLUMN "id" DROP DEFAULT,
                            ALTER COLUMN "updatedAt" DROP DEFAULT;

-- ── Foreign keys, restated with the ON UPDATE the schema declares ─────────────────────────────
--
-- Dropped and re-added rather than altered, because PostgreSQL has no ALTER CONSTRAINT for a
-- referential action. The ON DELETE action of each is unchanged — it is written out here so a
-- reviewer can see that for themselves rather than trust the sentence above.

ALTER TABLE "NexusKey" DROP CONSTRAINT "NexusKey_providerId_fkey";
ALTER TABLE "NexusKey" ADD  CONSTRAINT "NexusKey_providerId_fkey"
  FOREIGN KEY ("providerId") REFERENCES "NexusProvider"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NexusKey" DROP CONSTRAINT "NexusKey_ownerTeamId_fkey";
ALTER TABLE "NexusKey" ADD  CONSTRAINT "NexusKey_ownerTeamId_fkey"
  FOREIGN KEY ("ownerTeamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "NexusTeamKey" DROP CONSTRAINT "NexusTeamKey_teamId_fkey";
ALTER TABLE "NexusTeamKey" ADD  CONSTRAINT "NexusTeamKey_teamId_fkey"
  FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "DomainAlias" DROP CONSTRAINT "DomainAlias_teamId_fkey";
ALTER TABLE "DomainAlias" ADD  CONSTRAINT "DomainAlias_teamId_fkey"
  FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Last, and deliberately: this is the one that scans a large table.
ALTER TABLE "TokenUsage" DROP CONSTRAINT "TokenUsage_nexusTeamKeyId_fkey";
ALTER TABLE "TokenUsage" ADD  CONSTRAINT "TokenUsage_nexusTeamKeyId_fkey"
  FOREIGN KEY ("nexusTeamKeyId") REFERENCES "NexusTeamKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;
