/*
 * Copyright (c) 2026 Alayra Systems Pvt. Limited (Pakistan)
 * & Alayra Systems LLC (USA).
 *
 * Alayra Nexus™ is a trademark of Alayra Systems. Use of the name or logo
 * is not granted by the software license below.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * A copy of the License is in the LICENSE file at the repository root,
 * or at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
 * ANY KIND, either express or implied. See the License for details.
 */

// The numbers we intend to publish, generated by a tool the reader already trusts.
//
//   npm run build && npm run bench:k6
//
// ── Why k6 and not our own driver ─────────────────────────────────────────────────────────────
//
// Two reasons, and the second is the one that matters.
//
// Nobody accepts a vendor's own load generator. That is not unfair — it is the correct prior, and
// we would apply it to anybody else's numbers. k6 is what this industry actually uses, it is
// pinned to an exact version here, and a reader can run the same script against the same image.
//
// More importantly, our driver is closed-loop and therefore reports an optimistic tail. See the
// header of k6/openLoop.js for what coordinated omission is and why it makes a p99 gathered that
// way indefensible. Our driver stays for iterating on our own code, where a consistent measurement
// matters more than an absolute one. This is the one that gets published.
//
// ── The sweep, not a single number ────────────────────────────────────────────────────────────
//
// Open-loop testing has an arrival RATE rather than a concurrency, so a single run answers only
// "can it survive this rate". Sweeping the rate finds the point where the tail turns, which is the
// only capacity figure worth quoting: the highest rate at which the gateway still behaves.
//
// `droppedIterations` is the honest signal. k6 drops an iteration it cannot start on time, and
// `maxVUs` is set generously so a drop means the GATEWAY could not absorb the rate rather than
// that the generator ran out of workers.

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { NETWORK, rigDown, startRig } from './rig';
import { setUpstream } from './gateway';

// NOTE: k6/openLoop.js carries its own copy of the request body. It runs inside the k6 container
// and cannot import from here, so the two have to be kept in step by hand — if COMPLETION_BODY in
// gateway.ts changes, change it there too, or this scenario stops measuring the same request as
// every other one.

/** Pinned, because "we used k6" is not reproducible and "we used k6 v0.49.0" is. */
const K6_IMAGE = process.env.K6_IMAGE ?? 'grafana/k6:0.49.0';

const WORKERS = parseInt(process.env.BENCH_WORKERS ?? '1', 10);
const DURATION = process.env.K6_DURATION ?? '20s';
const RATES = (process.env.K6_RATES ?? '200,400,600,800,1000,1200')
  .split(',').map((n) => parseInt(n, 10)).filter((n) => n > 0);

interface K6Result {
  requestedRate: number;
  achievedRps: number;
  requests: number;
  failedRate: number;
  droppedIterations: number;
  med: number;
  p90: number;
  p95: number;
  p99: number;
  p999: number;
  max: number;
}

const SCRIPT = join(__dirname, 'k6', 'openLoop.js');

function runK6(rate: number, targetUrl: string, apiKey: string, duration: string): K6Result {
  const out = execFileSync('docker', [
    'run', '--rm', '-i',
    // On the SAME network as the gateway, which is the whole point. Reaching it through the host
    // instead put Docker Desktop's userspace NAT in the measurement: 88 ms p95 at 200 rps, then
    // connection refused. See the header of rig.ts.
    '--network', NETWORK,
    '-e', `RATE=${rate}`,
    '-e', `DURATION=${duration}`,
    '-e', `TARGET_URL=${targetUrl}`,
    '-e', `API_KEY=${apiKey}`,
    // Generous on purpose: a dropped iteration should mean the gateway could not absorb the rate,
    // never that k6 ran out of workers to send with.
    '-e', `PRE_VUS=${Math.min(Math.max(rate, 50), 400)}`,
    '-e', 'MAX_VUS=2000',
    K6_IMAGE, 'run', '-',
  ], {
    input: readFileSync(SCRIPT, 'utf8'),
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  });

  const line = out.split(/\r?\n/).find((l) => l.startsWith('NEXUS_K6_JSON:'));
  if (!line) throw new Error(`k6 produced no summary line. Output was:\n${out.slice(0, 2_000)}`);
  return JSON.parse(line.slice('NEXUS_K6_JSON:'.length)) as K6Result;
}

const ms = (n: number): string => (n < 10 ? n.toFixed(2) : n.toFixed(1));

async function main(): Promise<void> {
  const k6Version = execFileSync('docker', ['run', '--rm', K6_IMAGE, 'version'], { encoding: 'utf8' }).trim();

  const rig = await startRig({ workers: WORKERS });

  const results: K6Result[] = [];
  try {
    await setUpstream(rig.mockHostUrl, { latencyMs: 0 });
    const target = `${rig.internalUrl}/v1/chat/completions`;

    // Prove the container can actually reach the gateway before spending minutes discovering it
    // could not — the failure otherwise looks like "the gateway is infinitely slow".
    const probe = runK6(20, target, rig.apiKey, '3s');
    if (probe.requests === 0) throw new Error(`k6 reached the gateway zero times on ${target}`);

    // The rig's OWN ceiling, measured by pointing k6 straight at the mock with the gateway taken
    // out of the path. Without this a small machine reports the generator's limit as the gateway's,
    // which has already happened twice in this project — once when the load driver and the workers
    // shared four cores, and once when Docker Desktop's NAT was in the path. A number that cannot
    // tell those apart is not a measurement.
    const ceiling = runK6(
      Math.max(...RATES) * 2,
      `${rig.mockInternalUrl}/v1/chat/completions`,
      rig.apiKey,
      '10s',
    );
    console.log(
      `
rig ceiling: k6 → mock directly reached ${ceiling.achievedRps.toFixed(0)} rps ` +
      `(p99 ${ms(ceiling.p99)} ms, ${ceiling.droppedIterations} dropped). Any gateway row approaching ` +
      'this is measuring the rig, not Nexus.',
    );

    // One warmup, discarded. The first few thousand requests run before V8 has tiered anything up,
    // and folding that into the lowest rate in the sweep would make the curve start in the wrong
    // place.
    console.log(`\nwarming up (${WORKERS} worker${WORKERS === 1 ? '' : 's'})…`);
    runK6(Math.max(...RATES) / 2, target, rig.apiKey, '10s');

    for (const rate of RATES) {
      const r = runK6(rate, target, rig.apiKey, DURATION);
      results.push(r);
      console.log(
        `  ${String(rate).padStart(5)} rps requested → ${r.achievedRps.toFixed(0)} achieved, ` +
        `p50 ${ms(r.med)} p95 ${ms(r.p95)} p99 ${ms(r.p99)} p99.9 ${ms(r.p999)}, ` +
        `${r.droppedIterations} dropped, ${(r.failedRate * 100).toFixed(2)}% failed`,
      );
    }
  } finally {
    rig.dispose();
  }

  console.log(`\n── open-loop, ${k6Version} ──`);
  console.log(`── ${WORKERS} worker${WORKERS === 1 ? '' : 's'}, Postgres + Redis, ${DURATION} per rate ──\n`);
  console.log('| requested rps | achieved | p50 ms | p95 ms | p99 ms | p99.9 ms | max ms | dropped | failed |');
  console.log('|---|---|---|---|---|---|---|---|---|');
  for (const r of results) {
    console.log(
      `| ${r.requestedRate} | ${r.achievedRps.toFixed(0)} | ${ms(r.med)} | ${ms(r.p95)} | ${ms(r.p99)} | ` +
      `${ms(r.p999)} | ${ms(r.max)} | ${r.droppedIterations} | ${(r.failedRate * 100).toFixed(2)}% |`,
    );
  }

  // The capacity figure, stated rather than left to be read off the table. "Behaves" is defined
  // here as: no dropped iterations, no failures, and a tail that has not yet run away.
  const healthy = results.filter((r) => r.droppedIterations === 0 && r.failedRate === 0 && r.p99 < 1_000);
  const best = healthy[healthy.length - 1];
  console.log('');
  if (best) {
    console.log(
      `Highest rate sustained cleanly: ${best.requestedRate} rps ` +
      `(p99 ${ms(best.p99)} ms, p99.9 ${ms(best.p999)} ms, no drops, no errors).`,
    );
  } else {
    console.log('No rate in this sweep was sustained cleanly — lower the range with K6_RATES.');
  }
  if (results.length > 0 && healthy.length === results.length) {
    console.log('Every rate held: the sweep did not reach the ceiling. Raise K6_RATES to find it.');
  }
  console.log('');
}

main().catch((e) => { console.error(e); rigDown(); process.exit(1); });
